version: "3.3"

services:
  redis:
    image: redis:latest
    container_name: 'redis-container'
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - /path/to/local/d–∞ta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=password # move to .env
      - REDIS_PORT=6379
      - REDIS_DATABASES=1
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'app-container'
    restart: unless-stopped
    ports:
      - "8080:8080"
    command: ./app
    depends_on:
      - redis
