env: "local" # local, prod
http_server:
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 60s
tt_server:
  address: "localhost:8081"
redis:
  address: "localhost:6379"
  password: ""
  db: 0
  expiration_period: 2h
