env: "local" # local, prod
http_server:
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 60s
timetable_api:
  address: "localhost:8081"
  timeout: 5s
redis:
  address: "localhost:6379"
  password: ""
  db: 0
  user_exp_period: 24h
  event_exp_period: 4h
